queue_rules:
  - name: default
    merge_conditions:
      - check-success=build (aarch64-darwin)
      - check-success=build (x86_64-linux)
      - check-success=deploy
defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
      method: rebase
pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - label~=merge-queue|dependencies
    actions:
      queue: {}
