INHERIT: !ENV MKDOCS_NUMTIDE_THEME

### Site metadata ###

site_name: srvos
site_description: NixOS profiles for servers
site_url: https://numtide.github.io/srvos/
repo_name: 'numtide/srvos'
repo_url: https://github.com/numtide/srvos
edit_uri: edit/main/docs

### Navigation ###

nav:
  - Hello: index.md
  - NixOS modules:
      - General: nixos/general.md
      - Hardware: nixos/hardware.md
      - Mixins: nixos/mixins.md
      - Roles:
        - GitHub Action Runner: nixos/roles/github_actions_runner.md
  - Installation:
      - Hetzner Cloud: installation/hetzner_cloud.md
