name: Nix
on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        system:
          - aarch64-darwin
          - x86_64-linux
    runs-on: [nix]
    steps:
      - uses: actions/checkout@v3
      - run: ./dev/ci.sh --argstr system ${{ matrix.system }}
